
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kütüphane_Otomasyonu
{

using System;
    using System.Collections.Generic;
    
public partial class Kayıtlar
{

    public int kayit_id { get; set; }

    public int kullanici_id { get; set; }

    public int kitap_id { get; set; }

    public System.DateTime alis_tarihi { get; set; }

    public System.DateTime son_teslim_tarihi { get; set; }

    public bool durum { get; set; }



    public virtual Kaynaklar Kaynaklar { get; set; }

    public virtual Kullanıcılar Kullanıcılar { get; set; }

}

}
