
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kütüphane_Otomasyonu
{

using System;
    using System.Collections.Generic;
    
public partial class Kullanıcılar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kullanıcılar()
    {

        this.Kayıtlar = new HashSet<Kayıtlar>();

    }


    public int kullanici_id { get; set; }

    public string kullanici_ad { get; set; }

    public string kullanici_soyad { get; set; }

    public string kullanici_tc { get; set; }

    public string kullanici_mail { get; set; }

    public string kullanici_tel { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kayıtlar> Kayıtlar { get; set; }

}

}
