

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kütüphane_Otomasyonu
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Kütüphane_OtomasyonuEntities : DbContext
{
    public Kütüphane_OtomasyonuEntities()
        : base("name=Kütüphane_OtomasyonuEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }

    public virtual DbSet<Personeller> Personeller { get; set; }

    public virtual DbSet<Kaynaklar> Kaynaklar { get; set; }

    public virtual DbSet<Kayıtlar> Kayıtlar { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

